version: '3'
services:
  backend:
    build: .
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URL=mongodb://mongo:27017/ecommerce
    container_name: exommerce-backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: exommerce-db
    ports:
      - '27017:27017'
